theme = "solarized-dark"

[icons]
name = "awesome5"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "networkmanager"
primary_only = true
device_format = "{icon}{ap} {ips}"
on_click = "alacritty -e nmtui"

[[block]]
block = "speedtest"
bytes = true
interval = 1800

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

